
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DevisionByZeroException", targetNamespace = "http://service.expressionproject/")
public class DevisionByZeroException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DevisionByZeroException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DevisionByZeroException_Exception(String message, DevisionByZeroException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DevisionByZeroException_Exception(String message, DevisionByZeroException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.DevisionByZeroException
     */
    public DevisionByZeroException getFaultInfo() {
        return faultInfo;
    }

}
